name: memo_app
description: "chat app that is able to send voice messages"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  audio_session: ^0.1.23
  permission_handler: ^11.3.1
  record: ^5.2.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  fpdart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3


flutter:
  uses-material-design: true

  assets:
    - assets/service_account.json ##replace with your file
